# Generated by Django 4.1.3 on 2022-11-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('descripcion', models.TextField(max_length=512)),
                ('imagen', models.ImageField(upload_to='')),
                ('fecha', models.DateField()),
            ],
        ),
    ]
