# Generated by Django 4.1.3 on 2022-11-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='new',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='new',
            name='imagen',
        ),
        migrations.AddField(
            model_name='new',
            name='date',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(default='none', upload_to='images/'),
            preserve_default=False,
        ),
    ]
